export const quotes: string[] = [
  "Every morning we are born again. What we do today is what matters most. – Gautama Buddha",
  "The longest journey begins with a single step. – Patanjali",
  "Be the change that you wish to see in the world. – Mahatma Gandhi",
  "Peace comes from within. Do not seek it without. – Gautama Buddha",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. – Buddha",
  "Happiness depends upon ourselves. – Aristotle",
  "He who is brave is free. – Seneca",
  "Knowing yourself is the beginning of all wisdom. – Aristotle",
  "You have power over your mind – not outside events. Realize this, and you will find strength. – Marcus Aurelius",
  "The only thing I know is that I know nothing. – Socrates",
  "Act without expectation. – Lao Tzu",
  "Courage is resistance to fear, mastery of fear – not absence of fear. – Mark Twain",
  "An unexamined life is not worth living. – Socrates",
  "Do not spoil what you have by desiring what you have not. – Epicurus",
  "Be yourself; everyone else is already taken. – Oscar Wilde",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. – Aristotle",
  "To live is the rarest thing in the world. Most people exist, that is all. – Oscar Wilde",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "Knowing others is intelligence; knowing yourself is true wisdom. – Lao Tzu",
  "He who opens a school door, closes a prison. – Victor Hugo",
  "Be faithful in small things because it is in them that your strength lies. – Mother Teresa",
  "A man who has committed a mistake and doesn't correct it is committing another mistake. – Confucius",
  "You cannot shake hands with a clenched fist. – Indira Gandhi",
  "When you realize nothing is lacking, the whole world belongs to you. – Lao Tzu",
  "Life is really simple, but we insist on making it complicated. – Confucius",
  "To improve is to change; to be perfect is to change often. – Winston Churchill",
  "The more you know, the more you realize you don't know. – Aristotle",
  "Everything has beauty, but not everyone sees it. – Confucius",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
  "The best way out is always through. – Robert Frost",
  "The only true wisdom is in knowing you know nothing. – Socrates",
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
  "You must be the change you wish to see in the world. – Mahatma Gandhi",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
  "I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
  "The harder the conflict, the greater the triumph. – George Washington",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
  "Believe in yourself and all that you are. – Christian D. Larson",
  "Either you run the day or the day runs you. – Jim Rohn",
  "You miss 100% of the shots you don’t take. – Wayne Gretzky",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
  "You only live once, but if you do it right, once is enough. – Mae West",
  "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
  "A goal is a dream with a deadline. – Napoleon Hill",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "Be not afraid of going slowly, be afraid only of standing still. – Chinese Proverb",
  "When something is important enough, you do it even if the odds are not in your favor. – Elon Musk",
  "You do not find the happy life. You make it. – Camilla Eyring Kimball",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Only in the darkness can you see the stars. – Martin Luther King Jr.",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "The best way to predict your future is to create it. – Abraham Lincoln",
  "Happiness is not something ready-made. It comes from your own actions. – Dalai Lama"
];
